### PR TITLE
Add copy CLI command buttons to templates

### LINKED ISSUE #70: Add `create astro --template` commands to dropdown
It would be a nice QOL enhancement to have a mechanism for users to directly copy a `create astro` command for a given template as outlined in https://docs.astro.build/en/install-and-setup/

### PR DESCRIPTION
**Pull request by delucis**
This PR adds a “Copy CLI command” button to each template on astro.new to make it easier to run `create astro` for a specific template (instead of opening in a web IDE).

Closes #70 
Closes DX-1474

Looks like this:

card component with a screenshot, large title text, a small source code link with GitHub icon, a small copy CLI command butonn with clipboard icon, and a large blue-purple Open in StackBlitz button

(The first relevant commit is f19fb40 — the others are still left over from #74)

Tested in Chrome, Firefox & Safari on macOS, and Firefox Android.

### CODE REVIEW

**Review by sarah11918 — APPROVED** [review]
Works for me @delucis ! I tried the copy button on a handful of the repos, including some of the other tabs, and the command worked every time for me! :muscle:

**Comment by HiDeoo** [comment]
Won't have time to make a full suggestion before T&D, but wanted to mention that the announcement is not great at the moment, e.g. this demo using VoiceOver with a duplicated label and the useless image.

https://github.com/user-attachments/assets/ca883bd2-67c8-413a-84b5-d04f1f4812cf

**Comment by delucis** [comment]
> Won't have time to make a full suggestion before T&D, but wanted to mention that the announcement is not great at the moment, e.g. this demo using VoiceOver with a duplicated label and the useless image.

Thank you! Was different for me when testing with VoiceOver in Chrome, but I did change some small details since then, so maybe it changed.

**Comment by delucis** [comment]
OK, at least added `aria-hidden="true"` to the icons. I confirmed this was an issue in Firefox (not in Chrome for me) with the useless “image” announcement. I’d forgotten `astro-icon` doesn’t do that by default.

**Pull request merged**
